@REM ----------------------------------------------------------------------------
@REM Maven Wrapper — used to bootstrap Maven-based builds without a global install.
@REM Generated by Codex for Online Booking System backend.
@REM ----------------------------------------------------------------------------

@REM Stop if any command fails
@echo off

set DIRNAME=%~dp0
set APP_BASE_NAME=%~n0
set WRAPPER_JAR=%DIRNAME%.mvn\wrapper\maven-wrapper.jar
set WRAPPER_PROPERTIES=%DIRNAME%.mvn\wrapper\maven-wrapper.properties

@REM Download maven-wrapper.jar if not present
if exist "%WRAPPER_JAR%" goto run

echo Downloading Maven Wrapper JAR...
@powershell -Command "& {Invoke-WebRequest -Uri 'https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.2/maven-wrapper-3.3.2.jar' -OutFile '%WRAPPER_JAR%'}"
if not exist "%WRAPPER_JAR%" (
    echo Failed to download Maven Wrapper. Please check your internet connection.
    exit /b 1
)

:run
@REM Execute Maven using the wrapper jar
"%JAVA_HOME%\bin\java.exe" -Dfile.encoding=UTF-8 ^
    -jar "%WRAPPER_JAR%" ^
    %*
if errorlevel 1 exit /b 1
